用户指南
----------

此部分先介绍了顶点云设备管理平台的背景，之后通过配置介绍、快速上手分析平台框架，最后介绍平台提供的接口。

.. toctree::
   :maxdepth: 2
	
   forewords
   dm-installation
   dm-config
   dm-quickstart
   dm-structual
   dm-blueprint
   dm-models
   dm-viewfunction
   dm-devices
   dm-client
   dm-ajax
   dm-test

其他材料
---------

此部分文档包括顶点云设备管理平台的设计要点和变动记录

.. toctree::
   :maxdepth: 2
   
   dm-design
   dm-log   

许可证信息
-------------

此部分标明顶点云设备管理平台使用的开源许可证以及授权声明。

.. toctree::
   :maxdepth: 2
   
   license
